import bcrypt from 'bcryptjs'
const data = {
  users: [
    {
      name: 'admin',
      email: 'admin@gmail.com',
      password: bcrypt.hashSync('password'),
      isAdmin: true,
    },
    {
      name: 'user',
      email: 'user@gmail.com',
      password: bcrypt.hashSync('password'),
      isAdmin: false,
    },
  ],
  products: [
    // choose random product image and banner from the internet
    {
      name: 'Free Shirt',
      slug: 'free-shirt',
      image: 'https://i.ibb.co/xJS0T3Y/Blue-Shirt.png',
      banner: 'https://i.ibb.co/DG69bQ4/Blue-Shirt.png',
      price: 70,
      brand: 'Apple',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular shirt',
      category: 'Shirts',
      isFeatured: true,
    },
    {
      name: 'Fit Shirt',
      slug: 'fit-shirt',
      image: 'https://i.ibb.co/55z32tw/Black-Shirt.png',
      banner: 'https://i.ibb.co/55z32tw/Black-Shirt.png',
      price: 80,
      brand: 'Apple',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular shirt',
      category: 'Shirts',
      isFeatured: true,
    },
    {
      name: 'Slim Shirt',
      slug: 'slim-shirt',
      image: 'https://i.ibb.co/0s3pdnc/Tan-Shirt.png',
      banner: 'https://i.ibb.co/0s3pdnc/Tan-Shirt.png',
      price: 90,
      brand: 'Apple',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular shirt',
      category: 'Shirts',
      isFeatured: true,
    },
    {
      name: 'Golf Pants',
      slug: 'golf-pants',
      image: 'https://i.ibb.co/0s3pdnc/Tan-Pants.png',
      banner: 'https://i.ibb.co/0s3pdnc/Tan-Pants.png',
      price: 90,
      brand: 'Apple',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Smart looking pants',
      category: 'Pants',
      isFeatured: true,
    },
    {
      name: 'Fit Pants',
      slug: 'fit-pants',
      image: 'https://i.ibb.co/Mhh6wBg/Black-Pants.png',
      banner: 'https://i.ibb.co/Mhh6wBg/Black-Pants.png',
      price: 70,
      brand: 'Apple',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular pants',
      category: 'Pants',
      isFeatured: true,
    },
    {
      name: 'Slim Pants',
      slug: 'slim-pants',
      image: 'https://i.ibb.co/Mhh6wBg/Black-Pants.png',
      banner: 'https://i.ibb.co/Mhh6wBg/Black-Pants.png',
      price: 65,
      brand: 'Apple',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular pants',
      category: 'Pants',
      isFeatured: true,
    },
  ],
}

export default data
